server.port: 5555
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true                
spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
      - id: LicensingService
        uri: lb://Licensing-Service/
        predicates:
        - Path=/Licensing/**
        filters:
        - TokenRelay=
      - id: OrganizationService
        uri: lb://Organization-Service/
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/SpringBootKeycloakApp/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/SpringBootKeycloakApp/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8080/auth/realms/SpringBootKeycloakApp/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-test-scope:
            provider: keycloak
            client-id: SpringBoot-MicroService
            client-secret: 397f65b3-a418-4db9-afda-5d20e2c4af52
            authorization-grant-type: authorization_code
            redirect-uri: {baseUrl}/login/oauth2/code/keycloak
          keycloak-without-test-scope:
            provider: keycloak
            client-id: SpringBoot-MicroService
            client-secret: 397f65b3-a418-4db9-afda-5d20e2c4af52
            authorization-grant-type: authorization_code
            redirect-uri: {baseUrl}/login/oauth2/code/keycloak
