server.port: 5555
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true                
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: LicensingService
        uri: lb://Licensing-Service/
        predicates:
        - Path=/Licensing/**
        filters:
        - RewritePath=/Licensing/(?<path>.*), /$\{path}
      - id: OrganizationService
        uri: lb://Organization-Service/
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
management:
  endpoints:
    web:
      exposure:
        include: "*"
keycloak.realm: SpringBootKeycloakApp
keycloak.auth-server-url: http://localhost:8080/auth
keycloak.ssl-required: external
keycloak.resource: SpringBoot-MicroService
keycloak.credentials.secret: 397f65b3-a418-4db9-afda-5d20e2c4af52
keycloak.use-resource-role-mappings: true
keycloak.bearer-only: true
logging.level.org.keycloak=TRACE
