server.port: 5555
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true                
spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloack:
            provider: keycloak
            client-id: SpringBoot-MicroService
            client-secret: 397f65b3-a418-4db9-afda-5d20e2c4af52
            authorization-grant-type: authorization_code
            client-authentication-method: public
          #  redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
#            scope: openid,profile,email,resource.read,offline_access
        provider:
          keycloak:
            #token-uri: http://localhost:8080/auth/realms/SpringBootKeycloakApp/protocol/openid-connect/token
            #authorization-uri: http://localhost:8080/auth/realms/SpringBootKeycloakApp/protocol/openid-connect/auth
            #userinfo-uri: http://localhost:8080/auth/realms/SpringBootKeycloakApp/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8080/auth/realms/SpringBootKeycloakApp
            #user-name-attribute: preferred_username
#            jwk-set-uri: http://uaa:8090/uaa/token_keys

  cloud:
    gateway:
      default-filters:
      - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
      - id: LicensingService
        uri: lb://Licensing-Service/
        predicates:
        - Path=/Licensing/**
        filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/organization/(?<path>.*), /$\{path}

        #filters:
        #- RewritePath=/Licensing/(?<path>.*), /$\{path}
      - id: OrganizationService
        uri: lb://Organization-Service/
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
