server.port: 5555
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true                
spring:
  zipkin.baseUrl:  http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: LicensingService
        uri: lb://Licensing-Service/
        predicates:
        - Path=/Licensing/**
        filters:
        - RewritePath=/Licensing/(?<path>.*), /$\{path}
      - id: OrganizationService
        uri: lb://Organization-Service/
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
logging.level.org.springframework.cloud.sleuth: DEBUG
